// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwZhB66NXfloRPq8O99UbD5S-g44H8LQk',
    appId: '1:442962390280:android:8ea2c1ff2cae00d784d0bd',
    messagingSenderId: '442962390280',
    projectId: 'tremble-dev',
    storageBucket: 'tremble-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkJN_8fqHZVW62706LqtXz_x2AuBEHvYE',
    appId: '1:442962390280:ios:96b40f5a97e99f5384d0bd',
    messagingSenderId: '442962390280',
    projectId: 'tremble-dev',
    storageBucket: 'tremble-dev.firebasestorage.app',
    androidClientId:
        '442962390280-u6hq3im5h9kbtmvl1u0tclckk7765nbh.apps.googleusercontent.com',
    iosClientId:
        '442962390280-6qd7h0n5hetk6iv4norsl5bnghi7gqod.apps.googleusercontent.com',
    iosBundleId: 'com.pulse',
  );
}
