// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DevFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DevFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DevFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVsaxk3U0BfZ1YDXoDZP2gPryeQMmUi64',
    appId: '1:442962390280:web:0f0fe746708b51dd84d0bd',
    messagingSenderId: '442962390280',
    projectId: 'tremble-dev',
    authDomain: 'tremble-dev.firebaseapp.com',
    storageBucket: 'tremble-dev.firebasestorage.app',
    measurementId: 'G-0Z8H4TJMF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwZhB66NXfloRPq8O99UbD5S-g44H8LQk',
    appId: '1:442962390280:android:4078115ccb35217884d0bd',
    messagingSenderId: '442962390280',
    projectId: 'tremble-dev',
    storageBucket: 'tremble-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkJN_8fqHZVW62706LqtXz_x2AuBEHvYE',
    appId: '1:442962390280:ios:96b40f5a97e99f5384d0bd',
    messagingSenderId: '442962390280',
    projectId: 'tremble-dev',
    storageBucket: 'tremble-dev.firebasestorage.app',
    iosClientId: '442962390280-6qd7h0n5hetk6iv4norsl5bnghi7gqod.apps.googleusercontent.com',
    iosBundleId: 'com.pulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkJN_8fqHZVW62706LqtXz_x2AuBEHvYE',
    appId: '1:442962390280:ios:96b40f5a97e99f5384d0bd',
    messagingSenderId: '442962390280',
    projectId: 'tremble-dev',
    storageBucket: 'tremble-dev.firebasestorage.app',
    iosClientId: '442962390280-6qd7h0n5hetk6iv4norsl5bnghi7gqod.apps.googleusercontent.com',
    iosBundleId: 'com.pulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVsaxk3U0BfZ1YDXoDZP2gPryeQMmUi64',
    appId: '1:442962390280:web:df8e6dd74362a16b84d0bd',
    messagingSenderId: '442962390280',
    projectId: 'tremble-dev',
    authDomain: 'tremble-dev.firebaseapp.com',
    storageBucket: 'tremble-dev.firebasestorage.app',
    measurementId: 'G-NLEBHG1Z48',
  );
}
