// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class ProdFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'ProdFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'ProdFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP5paijbd6zFT7s-22bJtkigeuXM3-9ak',
    appId: '1:343655004163:web:d93230c3a60036d4fc3636',
    messagingSenderId: '343655004163',
    projectId: 'am---dating-app',
    authDomain: 'am---dating-app.firebaseapp.com',
    storageBucket: 'am---dating-app.firebasestorage.app',
    measurementId: 'G-6X9V5YL2GN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKwli4V13Vy0mgJfEQdxOWaiSc_ZnpEFc',
    appId: '1:343655004163:android:b9b9e2087fedf2b8fc3636',
    messagingSenderId: '343655004163',
    projectId: 'am---dating-app',
    storageBucket: 'am---dating-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdiulWWLO1EP5WH-EXbfgzCpEB4vrRmds',
    appId: '1:343655004163:ios:7a676f6d34be2a15fc3636',
    messagingSenderId: '343655004163',
    projectId: 'am---dating-app',
    storageBucket: 'am---dating-app.firebasestorage.app',
    androidClientId: '343655004163-45bpcekuulhjjo9q6pf8r46at2g18idp.apps.googleusercontent.com',
    iosClientId: '343655004163-sh9kf0e8cmnslmvg8gfts17rrdf2dql3.apps.googleusercontent.com',
    iosBundleId: 'com.pulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdiulWWLO1EP5WH-EXbfgzCpEB4vrRmds',
    appId: '1:343655004163:ios:7a676f6d34be2a15fc3636',
    messagingSenderId: '343655004163',
    projectId: 'am---dating-app',
    storageBucket: 'am---dating-app.firebasestorage.app',
    androidClientId: '343655004163-45bpcekuulhjjo9q6pf8r46at2g18idp.apps.googleusercontent.com',
    iosClientId: '343655004163-sh9kf0e8cmnslmvg8gfts17rrdf2dql3.apps.googleusercontent.com',
    iosBundleId: 'com.pulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP5paijbd6zFT7s-22bJtkigeuXM3-9ak',
    appId: '1:343655004163:web:5246ef4138c05e48fc3636',
    messagingSenderId: '343655004163',
    projectId: 'am---dating-app',
    authDomain: 'am---dating-app.firebaseapp.com',
    storageBucket: 'am---dating-app.firebasestorage.app',
    measurementId: 'G-PYHNY30R0L',
  );
}
